image: gitpod/workspace-full

# documentation from https://www.gitpod.io/docs/references/gitpod-yml

tasks:
  - name: Install Nextflow
    init: curl -s https://get.nextflow.io | bash
    command: chmod +x nextflow && mv nextflow /home/gitpod/.local/bin/.
